spring:
  application:
    name: MSAShop_User
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
      dynamic-update: true
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    name: testdb
  session:
    store-type: jdbc
    timeout: 30
logging:
  level:
    org:
      hibernate:
        type: debug
    com:
      msa: debug
server:
  port: 8082
kafka:
  bootstrap-servers: localhost:9092
  client-id: 0
  template:
    default-topic: msashop
  consumer:
    group-id: 0
